### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by cthoyt** [obophenotype/chebi_obo_slim#3]
- how instructions on how to rebuild ChEBI slim
   - what needs to be installed first?
   - what commands need to be run? 
- add contribution guidelines (how does one add additional terms? are there guidelines for keeping the `seeds.txt` file canonicalized?)

**Comment by matentzn** [comment]
What about: 

https://github.com/obophenotype/chebi_obo_slim/blob/main/README.md

**Comment by cthoyt** [comment]
Excellent :)

closed in 32703658e8f58ed47857498087bf76f7ca1fa163
